// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Funnier {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class UserSettings {
        
        private string lastViewedPhotoIdField;
        
        private string[] viewedPhotoIdsField;
        
        private string[] favoritePhotoIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LastViewedPhotoId {
            get {
                return this.lastViewedPhotoIdField;
            }
            set {
                this.lastViewedPhotoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ViewedPhotoIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ViewedPhotoIds {
            get {
                return this.viewedPhotoIdsField;
            }
            set {
                this.viewedPhotoIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FavoritePhotoIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] FavoritePhotoIds {
            get {
                return this.favoritePhotoIdsField;
            }
            set {
                this.favoritePhotoIdsField = value;
            }
        }
    }
}
